FROM ubuntu:16.04

RUN apt-get update -y && apt-get install -y \
    apt-transport-https \
    ca-certificates

RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys CE7709D068DB5E88
RUN bash -c 'echo "deb https://repo.sovrin.org/deb xenial stable" >> /etc/apt/sources.list'

RUN apt-get update -y && apt-get install -y \
    indy-node=1.12.6 \
    indy-plenum=1.12.6 \
    && rm -rf /var/lib/apt/lists/*

RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-keys CE7709D068DB5E88 && bash -c 'echo "deb https://repo.sovrin.org/sdk/deb xenial stable" >> /etc/apt/sources.list'
RUN apt-get update && apt-get install -y indy-cli

RUN awk '{if (index($1, "NETWORK_NAME") != 0) {print("NETWORK_NAME = \"'$INDY_NETWORK_NAME'\"")} else print($0)}' /etc/indy/indy_config.py> /tmp/indy_config.py
RUN mv /tmp/indy_config.py /etc/indy/indy_config.py

WORKDIR /home/indy

CMD ["bash"]